// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngdotwphrhuyfgqozqvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZG90d3Bocmh1eWZncW96cXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Nzg0NTksImV4cCI6MjA2MjA1NDQ1OX0.y7K1Taavs89nNgZzcLyl_rxCjrA72WL5Ep2xahYgO14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);